apiVersion: apps/v1
kind: Deployment
metadata:
  name: omen
  labels:
    app: omen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omen
  template:
    metadata:
      labels:
        app: omen
    spec:
      containers:
        - name: omen
          image: ghcr.io/jnqa/omen:
          ports:
            - containerPort: 3000
          env:
            - name: SOME_ENV
              value: Uselessphrase2

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 3

      imagePullSecrets:
        - name: dockerconfigjson-github-com