apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: IMAGENAME
  newName: ghcr.io/zebrainy/api-proxy-service
  newTag: v0.2.5
- name: api-proxy-service
  newName: ghcr.io/zebrainy/api-proxy-service
  newTag: v0.3.0
resources:
- ../../base
