name: Release application

on:
  push:
    branches:
      - test

jobs:
  call-workflow-passing-data:
    uses: jnqa/kuber/.github/workflows/test.yaml@test
    with:
      SERVICE_NAME: test-yo
    secrets:
      DEMO: ${{ secrets.DEMO }}