name: schedule

on:
  push:
    branches:
    - 'no'
  schedule:
    - cron: '5,6,7,8 10 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Every time
      run: echo "This step will always run"