name: schedule

on:
  push:
    # branches:
    # - 'no'
  schedule:
    - cron: '12,17,24 10 * * *'
    - cron: '* 10 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Every time
      run: echo "This step will always run"