name: schedule

on:
  push:
    # branches:
    # - 'no'
  schedule:
    - cron: '8,9,10,11 10 * * *'
    - cron: '* 10 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Every time
      run: echo "This step will always run"